[package]
name = "game"
version = "0.1.0"
edition = "2024"
default-run = "katla"

[features]
vulkan = ["katla_app/vulkan"]
metal = ["katla_app/metal"]

[[bin]]
name = "katla"
path = "src/main.rs"

[dependencies]
katla_app = { workspace = true }
katla_ecs = { workspace = true }
katla_script = { workspace = true }
clap = { workspace = true }
log = { workspace = true }
env_logger = { workspace = true }
