[package]
name = "rust_shared_ctx"
version = "0.1.0"
authors = ["Mik-pe <mikael.pettersson201@gmail.com>"]
edition = "2018"
# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
byteorder = "1.3"
mikpe_math = {git = "https://github.com/Mik-pe/mikpe_math.git"}
winit = "^0.23.0"
erupt = "^0.15.0"
lazy_static = "1.4.0"
image = "0.22.3"
itertools = "0.9.0"
# imgui = "^0.3.0"
# imgui-winit-support = "^0.3.0"



[dependencies.gltf]
features = ["KHR_materials_pbrSpecularGlossiness"]
version = "0.15"
