[package]
name = "katla_ui"
version = "0.1.0"
edition = "2024"

[dependencies]
katla_icons = { workspace = true }
katla_math = { workspace = true }
log = { workspace = true }
bitflags = { workspace = true }
bytemuck = { workspace = true }
slotmap = "1.0"
taffy = "0.7"

# Font handling
skrifa = { workspace = true }
vello_cpu = { workspace = true }

serde = { workspace = true }
serde_json = { workspace = true }

[dev-dependencies]
