[package]
name = "katla_app"
version = "0.1.0"
authors = ["Mik-pe <mikael.pettersson201@gmail.com>"]
edition = "2024"

[dependencies]
katla_math = { workspace = true }
katla_gfx = { workspace = true }
katla_ecs = { workspace = true }
katla_ui = { workspace = true }
katla_derive = { workspace = true }
ash = { workspace = true }
bytemuck = { workspace = true }
byteorder = { workspace = true }
winit = { workspace = true }
image = { workspace = true }
env_logger = { workspace = true }
gltf = { workspace = true }
itertools = { workspace = true }
approx = { workspace = true }
log = { workspace = true }
clap = { workspace = true }
dirs = { workspace = true }
png = { workspace = true }
ron = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
