[package]
name = "katla_ecs"
version = "0.1.0"
authors = ["Mik-pe <mikael.pettersson201@gmail.com>"]
edition = "2024"

[features]
editor = ["serde_json"]

[dependencies]
katla_derive = { workspace = true }
paste = { workspace = true }
rayon = "1.10"
serde_json = { workspace = true, optional = true }

[dev-dependencies]
criterion = "0.5"

[[bench]]
name = "ecs_benchmarks"
harness = false
