[package]
name = "katla_ecs"
version = "0.1.0"
authors = ["Mik-pe <mikael.pettersson201@gmail.com>"]
edition = "2024"

[features]
editor = ["serde_json"]

[dependencies]
katla_derive = { workspace = true }
rayon = { workspace = true }
serde_json = { workspace = true, optional = true }

[dev-dependencies]
criterion = "0.5"

[[bench]]
name = "ecs_benchmarks"
harness = false

[[bench]]
name = "ecs_comparison"
harness = false

[lints.rust]
unexpected_cfgs = { level = "warn", check-cfg = ['cfg(katla_ecs_baseline)'] }
