pub(crate) mod animation;
pub(crate) mod argument_buffer;
pub(crate) mod argument_state;
#[cfg(test)]
mod attachment_tests;
pub(crate) mod attachments;
pub(crate) mod binding_schema;
pub(crate) mod blit_encoder;
pub(crate) mod buffer;
mod buffer_history_retirement;
#[cfg(test)]
mod builtin_compute_tests;
pub(crate) mod command_buffer;
pub(crate) mod compute_encoder;
pub(crate) mod context;
pub(crate) mod depth_prepass;
pub(crate) mod diagnostics;
pub(crate) mod draw_helpers;
pub(crate) mod encoding_resources;
pub(crate) mod execution_plan;
pub(crate) mod font_atlas;
pub(crate) mod format;
pub(crate) mod frame_lifecycle;
pub(crate) mod frame_render;
#[cfg(test)]
mod frame_slot_tests;
mod graphics_preflight;
pub(crate) mod init_pipelines;
pub(crate) mod light_culling;
pub(crate) mod material_api;
pub(crate) mod mesh_api;
pub(crate) mod metal_renderer;
pub(crate) mod metal_transient_texture;
pub(crate) mod outline;
pub(crate) mod particle;
pub(crate) mod picking;
pub(crate) mod pipeline;
pub(crate) mod pipeline_archive;
pub(crate) mod render_encoder;
pub(crate) mod render_targets;
pub(crate) mod residency;
pub(crate) mod sampler;
pub(crate) mod shader;
pub(crate) mod shadow;
pub(crate) mod skeleton_api;
pub(crate) mod submission;
pub(crate) mod surface;
pub(crate) mod sync;
pub(crate) mod texture;
pub(crate) mod texture_api;
pub(crate) mod texture_upload;
pub(crate) mod timestamp_queries;
pub(crate) mod transient_heap;
pub(crate) mod ui_renderer;
pub(crate) mod viewport_api;

pub(crate) use context::MetalBackend;
