pub mod animation;
pub mod application;
pub mod components;
pub mod entities;
pub mod error;
pub mod gui_state;
pub mod input;
pub mod material;
pub mod preferences;
pub mod rendering;
pub mod resources;
pub mod systems;
mod ui;
mod util;

pub use error::{AppError, AppResult};
pub use gui_state::GuiState;
pub use katla_gfx::renderer::FrameUniforms;
pub use material::{texture_slots, PbrMaterialBuilder, PbrParams};
pub use preferences::Preferences;
pub use rendering::FrameContext;
