//! Application preferences with persistent storage.

use std::io;

use log::{debug, warn};

use crate::ui::Theme;

/// Application preferences that persist between sessions.
#[derive(Debug, Clone)]
pub struct Preferences {
    /// Currently selected theme name.
    pub theme: String,
    /// Show the grid in the viewport.
    pub show_grid: bool,
    /// Show the stats panel.
    pub show_stats: bool,
    /// Font scale multiplier (1.0 = 100%, 1.25 = 125%, etc.)
    pub font_scale: f32,
}

impl Default for Preferences {
    fn default() -> Self {
        Self {
            theme: "catppuccin".to_string(),
            show_grid: true,
            show_stats: true,
            font_scale: 1.0,
        }
    }
}

impl Preferences {
    /// Load preferences from disk, or return defaults if not found.
    pub fn load() -> Self {
        let content = match crate::util::load_config_file("preferences.toml") {
            Some(c) => c,
            None => {
                warn!("Could not load preferences file");
                return Self::default();
            }
        };

        Self::parse_toml(&content)
    }

    /// Save preferences to disk.
    pub fn save(&self) -> io::Result<()> {
        crate::util::save_config_file("preferences.toml", &self.to_toml())
    }

    /// Parse preferences from TOML content.
    fn parse_toml(content: &str) -> Self {
        let mut prefs = Self::default();

        for line in content.lines() {
            let line = line.trim();

            // Skip comments and empty lines
            if line.starts_with('#') || line.is_empty() {
                continue;
            }

            // Parse key = value
            if let Some((key, value)) = line.split_once('=') {
                let key = key.trim();
                let value = value.trim().trim_matches('"');

                match key {
                    "theme" => {
                        // Validate theme exists
                        if Theme::by_name(value).is_some() {
                            prefs.theme = value.to_string();
                        } else {
                            warn!("Unknown theme '{}', using default", value);
                        }
                    }
                    "show_grid" => {
                        prefs.show_grid = value.parse().unwrap_or(true);
                    }
                    "show_stats" => {
                        prefs.show_stats = value.parse().unwrap_or(true);
                    }
                    "font_scale" => {
                        let scale: f32 = value.parse().unwrap_or(1.0);
                        prefs.font_scale = scale.clamp(0.5, 3.0);
                    }
                    _ => {
                        debug!("Unknown preference key: {}", key);
                    }
                }
            }
        }

        prefs
    }

    /// Convert preferences to TOML content.
    fn to_toml(&self) -> String {
        format!(
            r#"# Katla Engine Preferences
# This file is automatically generated and reloaded.

# Color theme: catppuccin, nord, tokyo_night, dracula, gruvbox, default_dark
theme = "{}"

# Show the grid in the 3D viewport
show_grid = {}

# Show the stats panel
show_stats = {}

# Font scale multiplier (0.5 = 50%, 1.0 = 100%, 2.0 = 200%)
font_scale = {}
"#,
            self.theme, self.show_grid, self.show_stats, self.font_scale
        )
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_default_preferences() {
        let prefs = Preferences::default();
        assert_eq!(prefs.theme, "catppuccin");
        assert!(prefs.show_grid);
        assert!(prefs.show_stats);
        assert_eq!(prefs.font_scale, 1.0);
    }

    #[test]
    fn test_parse_toml() {
        let content = r#"
theme = "nord"
show_grid = false
show_stats = true
font_scale = 1.25
"#;
        let prefs = Preferences::parse_toml(content);
        assert_eq!(prefs.theme, "nord");
        assert!(!prefs.show_grid);
        assert!(prefs.show_stats);
        assert_eq!(prefs.font_scale, 1.25);
    }

    #[test]
    fn test_to_toml() {
        let prefs = Preferences {
            theme: "dracula".to_string(),
            show_grid: false,
            show_stats: true,
            font_scale: 1.5,
        };
        let toml = prefs.to_toml();
        assert!(toml.contains("theme = \"dracula\""));
        assert!(toml.contains("show_grid = false"));
        assert!(toml.contains("font_scale = 1.5"));
    }

    #[test]
    fn test_invalid_theme_uses_default() {
        let content = "theme = \"nonexistent\"";
        let prefs = Preferences::parse_toml(content);
        assert_eq!(prefs.theme, "catppuccin");
    }
}
