//! Application preferences with persistent storage.
//!
//! Stores user preferences in an OS-appropriate location:
//! - Windows: `C:\Users\<user>\AppData\Roaming\katla\preferences.toml`
//! - macOS: `~/Library/Application Support/katla/preferences.toml`
//! - Linux: `~/.config/katla/preferences.toml`

use std::fs;
use std::io::{self, Read, Write};
use std::path::PathBuf;

use log::{debug, info, warn};

use crate::ui::Theme;

/// Application preferences that persist between sessions.
#[derive(Debug, Clone)]
pub struct Preferences {
    /// Currently selected theme name.
    pub theme: String,
    /// Show the grid in the viewport.
    pub show_grid: bool,
    /// Show the stats panel.
    pub show_stats: bool,
}

impl Default for Preferences {
    fn default() -> Self {
        Self {
            theme: "catppuccin".to_string(),
            show_grid: true,
            show_stats: true,
        }
    }
}

impl Preferences {
    /// Get the preferences directory path for the current OS.
    pub fn config_dir() -> Option<PathBuf> {
        dirs::config_dir().map(|p| p.join("katla"))
    }

    /// Get the preferences file path.
    pub fn file_path() -> Option<PathBuf> {
        Self::config_dir().map(|p| p.join("preferences.toml"))
    }

    /// Load preferences from disk, or return defaults if not found.
    pub fn load() -> Self {
        let path = match Self::file_path() {
            Some(p) => p,
            None => {
                warn!("Could not determine preferences file path");
                return Self::default();
            }
        };

        if !path.exists() {
            debug!("Preferences file not found, using defaults");
            return Self::default();
        }

        let mut content = String::new();
        if let Err(e) = fs::File::open(&path).and_then(|mut f| f.read_to_string(&mut content)) {
            warn!("Failed to read preferences file: {}", e);
            return Self::default();
        }

        Self::parse_toml(&content)
    }

    /// Save preferences to disk.
    pub fn save(&self) -> io::Result<()> {
        let config_dir = Self::config_dir().ok_or_else(|| {
            io::Error::new(io::ErrorKind::NotFound, "Could not determine config directory")
        })?;

        // Create the config directory if it doesn't exist
        if !config_dir.exists() {
            fs::create_dir_all(&config_dir)?;
            info!("Created config directory: {:?}", config_dir);
        }

        let path = Self::file_path().ok_or_else(|| {
            io::Error::new(io::ErrorKind::NotFound, "Could not determine preferences file path")
        })?;

        let content = self.to_toml();
        let mut file = fs::File::create(&path)?;
        file.write_all(content.as_bytes())?;

        debug!("Saved preferences to {:?}", path);
        Ok(())
    }

    /// Parse preferences from TOML content.
    fn parse_toml(content: &str) -> Self {
        let mut prefs = Self::default();

        for line in content.lines() {
            let line = line.trim();

            // Skip comments and empty lines
            if line.starts_with('#') || line.is_empty() {
                continue;
            }

            // Parse key = value
            if let Some((key, value)) = line.split_once('=') {
                let key = key.trim();
                let value = value.trim().trim_matches('"');

                match key {
                    "theme" => {
                        // Validate theme exists
                        if Theme::by_name(value).is_some() {
                            prefs.theme = value.to_string();
                        } else {
                            warn!("Unknown theme '{}', using default", value);
                        }
                    }
                    "show_grid" => {
                        prefs.show_grid = value.parse().unwrap_or(true);
                    }
                    "show_stats" => {
                        prefs.show_stats = value.parse().unwrap_or(true);
                    }
                    _ => {
                        debug!("Unknown preference key: {}", key);
                    }
                }
            }
        }

        prefs
    }

    /// Convert preferences to TOML content.
    fn to_toml(&self) -> String {
        format!(
            r#"# Katla Engine Preferences
# This file is automatically generated and reloaded.

# Color theme: catppuccin, nord, tokyo_night, dracula, gruvbox, default_dark
theme = "{}"

# Show the grid in the 3D viewport
show_grid = {}

# Show the stats panel
show_stats = {}
"#,
            self.theme, self.show_grid, self.show_stats
        )
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_default_preferences() {
        let prefs = Preferences::default();
        assert_eq!(prefs.theme, "catppuccin");
        assert!(prefs.show_grid);
        assert!(prefs.show_stats);
    }

    #[test]
    fn test_parse_toml() {
        let content = r#"
theme = "nord"
show_grid = false
show_stats = true
"#;
        let prefs = Preferences::parse_toml(content);
        assert_eq!(prefs.theme, "nord");
        assert!(!prefs.show_grid);
        assert!(prefs.show_stats);
    }

    #[test]
    fn test_to_toml() {
        let prefs = Preferences {
            theme: "dracula".to_string(),
            show_grid: false,
            show_stats: true,
        };
        let toml = prefs.to_toml();
        assert!(toml.contains("theme = \"dracula\""));
        assert!(toml.contains("show_grid = false"));
    }

    #[test]
    fn test_invalid_theme_uses_default() {
        let content = "theme = \"nonexistent\"";
        let prefs = Preferences::parse_toml(content);
        assert_eq!(prefs.theme, "catppuccin");
    }
}
