commands:
  install: cargo build
  typecheck: cargo check
  build: cargo build
  build-lib: cargo build --workspace --lib
  test: cargo test --workspace
  test-ecs: cargo test -p katla_ecs
  test-gfx: cargo test -p katla_gfx
  test-app: cargo test -p katla_app
  test-ui: cargo test -p katla_ui
  lint: cargo clippy --workspace -- -D warnings
  lint-fix: cargo clippy --fix
  fmt: cargo fmt
  fmt-check: cargo fmt --check
  check-gfx: cargo check -p katla_gfx
  check-app: cargo check -p katla_app
  check-ui: cargo check -p katla_ui
  run-limited: cargo run -- -s

services: {}
