[package]
name = "katla_script"
version = "0.1.0"
edition = "2024"

[features]
editor = ["katla_ecs/editor"]

[dependencies]
mlua = { version = "0.11", features = ["luau", "vendored", "serialize"] }
katla_ecs = { path = "../katla_ecs" }
katla_math = { path = "../katla_math" }
katla_derive = { path = "../katla_derive" }
log = { workspace = true }
serde = { workspace = true }
