[package]
name = "katla_derive"
version = "0.1.0"
authors = ["Mik-pe <mikael.pettersson201@gmail.com>"]
edition = "2024"

[lib]
proc-macro = true

[features]
editor = ["katla_ecs/editor"]

[dependencies]
syn = { workspace = true }
quote = { workspace = true }
proc-macro2 = { workspace = true }

[dev-dependencies]
katla_ecs = { workspace = true, features = ["editor"] }
