//! Vulkan renderer for UI draw lists.
//!
//! This renders UI elements using the draw list generated by UiContext.

use std::rc::Rc;

use ash::vk;
use katla_math::Vec2;
use katla_ui::{DrawList, UiVertex};
use katla_vulkan::{
    IndexBuffer, VertexBuffer, Texture, VulkanContext,
    render_graph::types::ImageFormat,
};

/// UI uniform buffer data (matches shader)
#[repr(C)]
#[derive(Clone, Copy, Debug)]
struct UiUniforms {
    screen_size: [f32; 2],
    _padding: [f32; 2],
}

/// Vulkan renderer for UI draw lists.
pub struct UiRenderer {
    context: Rc<VulkanContext>,
    pipeline: Option<vk::Pipeline>,
    pipeline_layout: Option<vk::PipelineLayout>,
    desc_set_layout: Option<vk::DescriptorSetLayout>,
    desc_pool: Option<vk::DescriptorPool>,
    desc_set: Option<vk::DescriptorSet>,
    vertex_buffer: Option<VertexBuffer>,
    index_buffer: Option<IndexBuffer>,
    uniform_buffer: Option<vk::Buffer>,
    uniform_allocation: Option<gpu_allocator::vulkan::Allocation>,
    white_texture: Option<Texture>,
    max_vertices: u32,
    max_indices: u32,
}

impl UiRenderer {
    /// Create a new UI renderer.
    pub fn new(context: Rc<VulkanContext>) -> Result<Self, UiRenderError> {
        Ok(Self {
            context,
            pipeline: None,
            pipeline_layout: None,
            desc_set_layout: None,
            desc_pool: None,
            desc_set: None,
            vertex_buffer: None,
            index_buffer: None,
            uniform_buffer: None,
            uniform_allocation: None,
            white_texture: None,
            max_vertices: 10000,
            max_indices: 30000,
        })
    }

    /// Initialize the renderer (create pipeline, buffers, etc.)
    pub fn init(&mut self, color_format: ImageFormat) -> Result<(), UiRenderError> {
        // Create white texture (1x1 white pixel)
        self.create_white_texture()?;

        // Create descriptor set layout, pool, and set
        self.create_descriptor_sets()?;

        // Create uniform buffer
        self.create_uniform_buffer()?;

        // Create vertex and index buffers
        self.create_buffers()?;

        // Create pipeline
        self.create_pipeline(color_format)?;

        // Update descriptor sets
        self.update_descriptor_sets()?;

        log::info!("UI renderer initialized");
        Ok(())
    }

    fn create_white_texture(&mut self) -> Result<(), UiRenderError> {
        // Create a 1x1 white pixel texture
        let white_pixel = vec![255u8, 255, 255, 255];
        let texture = Texture::create_image(
            self.context.clone(),
            1,
            1,
            ImageFormat::R8G8B8A8Srgb,
            &white_pixel,
        );
        self.white_texture = Some(texture);
        Ok(())
    }

    fn create_descriptor_sets(&mut self) -> Result<(), UiRenderError> {
        unsafe {
            // Create descriptor set layout
            // Binding 0: Uniform buffer (screen size)
            // Binding 1: Texture (font atlas / white texture)
            // Binding 2: Sampler
            let bindings = [
                vk::DescriptorSetLayoutBinding {
                    binding: 0,
                    descriptor_type: vk::DescriptorType::UNIFORM_BUFFER,
                    descriptor_count: 1,
                    stage_flags: vk::ShaderStageFlags::VERTEX,
                    p_immutable_samplers: std::ptr::null(),
                },
                vk::DescriptorSetLayoutBinding {
                    binding: 1,
                    descriptor_type: vk::DescriptorType::SAMPLED_IMAGE,
                    descriptor_count: 1,
                    stage_flags: vk::ShaderStageFlags::FRAGMENT,
                    p_immutable_samplers: std::ptr::null(),
                },
                vk::DescriptorSetLayoutBinding {
                    binding: 2,
                    descriptor_type: vk::DescriptorType::SAMPLER,
                    descriptor_count: 1,
                    stage_flags: vk::ShaderStageFlags::FRAGMENT,
                    p_immutable_samplers: std::ptr::null(),
                },
            ];

            let layout_info = vk::DescriptorSetLayoutCreateInfo::default()
                .bindings(&bindings);

            let desc_layout = self.context.device
                .create_descriptor_set_layout(&layout_info, None)
                .map_err(|e| UiRenderError::VulkanError(format!("Failed to create descriptor set layout: {}", e)))?;

            self.desc_set_layout = Some(desc_layout);

            // Create descriptor pool
            let pool_sizes = [
                vk::DescriptorPoolSize {
                    ty: vk::DescriptorType::UNIFORM_BUFFER,
                    descriptor_count: 1,
                },
                vk::DescriptorPoolSize {
                    ty: vk::DescriptorType::SAMPLED_IMAGE,
                    descriptor_count: 1,
                },
                vk::DescriptorPoolSize {
                    ty: vk::DescriptorType::SAMPLER,
                    descriptor_count: 1,
                },
            ];

            let pool_info = vk::DescriptorPoolCreateInfo::default()
                .pool_sizes(&pool_sizes)
                .max_sets(1);

            let desc_pool = self.context.device
                .create_descriptor_pool(&pool_info, None)
                .map_err(|e| UiRenderError::VulkanError(format!("Failed to create descriptor pool: {}", e)))?;

            self.desc_pool = Some(desc_pool);

            // Allocate descriptor set
            let alloc_info = vk::DescriptorSetAllocateInfo::default()
                .descriptor_pool(desc_pool)
                .set_layouts(&[desc_layout]);

            let desc_sets = self.context.device
                .allocate_descriptor_sets(&alloc_info)
                .map_err(|e| UiRenderError::VulkanError(format!("Failed to allocate descriptor set: {}", e)))?;

            self.desc_set = Some(desc_sets[0]);
        }

        Ok(())
    }

    fn create_uniform_buffer(&mut self) -> Result<(), UiRenderError> {
        let create_info = vk::BufferCreateInfo::default()
            .sharing_mode(vk::SharingMode::EXCLUSIVE)
            .usage(vk::BufferUsageFlags::UNIFORM_BUFFER)
            .size(std::mem::size_of::<UiUniforms>() as u64);

        let (buffer, allocation) = self.context.allocate_buffer(
            &create_info,
            gpu_allocator::MemoryLocation::CpuToGpu,
        );

        self.uniform_buffer = Some(buffer);
        self.uniform_allocation = Some(allocation);

        Ok(())
    }

    fn create_buffers(&mut self) -> Result<(), UiRenderError> {
        // Create vertex buffer
        let vertex_size = (self.max_vertices * std::mem::size_of::<UiVertex>() as u32) as u64;
        self.vertex_buffer = Some(VertexBuffer::new(
            self.context.clone(),
            vertex_size,
            self.max_vertices,
        ));

        // Create index buffer
        let index_size = (self.max_indices * std::mem::size_of::<u32>() as u32) as u64;
        self.index_buffer = Some(IndexBuffer::new(
            self.context.clone(),
            index_size,
            katla_vulkan::IndexType::Uint32,
            self.max_indices,
        ));

        Ok(())
    }

    fn create_pipeline(&mut self, color_format: ImageFormat) -> Result<(), UiRenderError> {
        unsafe {
            let vk_format: vk::Format = color_format.into();

            // Load shaders (we'll compile from WGSL at runtime)
            let vert_shader = self.compile_shader(
                include_str!("../../../resources/shaders/ui/ui.vert.wgsl"),
                naga::ShaderStage::Vertex,
            )?;
            let frag_shader = self.compile_shader(
                include_str!("../../../resources/shaders/ui/ui.frag.wgsl"),
                naga::ShaderStage::Fragment,
            )?;

            let shader_stages = [
                vk::PipelineShaderStageCreateInfo::default()
                    .stage(vk::ShaderStageFlags::VERTEX)
                    .module(vert_shader)
                    .name("vs_main"),
                vk::PipelineShaderStageCreateInfo::default()
                    .stage(vk::ShaderStageFlags::FRAGMENT)
                    .module(frag_shader)
                    .name("fs_main"),
            ];

            // Vertex input description
            // UiVertex: position (vec2), uv (vec2), color (vec4)
            let binding_desc = vk::VertexInputBindingDescription {
                binding: 0,
                stride: std::mem::size_of::<UiVertex>() as u32,
                input_rate: vk::VertexInputRate::VERTEX,
            };

            let attr_descs = [
                // position
                vk::VertexInputAttributeDescription {
                    binding: 0,
                    location: 0,
                    format: vk::Format::R32G32_SFLOAT,
                    offset: 0,
                },
                // uv
                vk::VertexInputAttributeDescription {
                    binding: 0,
                    location: 1,
                    format: vk::Format::R32G32_SFLOAT,
                    offset: 8,
                },
                // color
                vk::VertexInputAttributeDescription {
                    binding: 0,
                    location: 2,
                    format: vk::Format::R32G32B32A32_SFLOAT,
                    offset: 16,
                },
            ];

            let vertex_input_info = vk::PipelineVertexInputStateCreateInfo::default()
                .vertex_binding_descriptions(&[binding_desc])
                .vertex_attribute_descriptions(&attr_descs);

            let input_assembly = vk::PipelineInputAssemblyStateCreateInfo::default()
                .topology(vk::PrimitiveTopology::TRIANGLE_LIST)
                .primitive_restart_enable(false);

            // Viewport and scissor will be set dynamically
            let viewport_state = vk::PipelineViewportStateCreateInfo::default()
                .viewport_count(1)
                .scissor_count(1);

            let rasterizer = vk::PipelineRasterizationStateCreateInfo::default()
                .depth_clamp_enable(false)
                .rasterizer_discard_enable(false)
                .polygon_mode(vk::PolygonMode::FILL)
                .line_width(1.0)
                .cull_mode(vk::CullModeFlags::NONE)
                .front_face(vk::FrontFace::CLOCKWISE);

            let multisampling = vk::PipelineMultisampleStateCreateInfo::default()
                .sample_shading_enable(false)
                .rasterization_samples(vk::SampleCountFlags::TYPE_1);

            // Depth test disabled for UI
            let depth_stencil = vk::PipelineDepthStencilStateCreateInfo::default()
                .depth_test_enable(false)
                .depth_write_enable(false);

            // Alpha blending
            let color_blend_attachment = vk::PipelineColorBlendAttachmentState {
                color_write_mask: vk::ColorComponentFlags::R
                    | vk::ColorComponentFlags::G
                    | vk::ColorComponentFlags::B
                    | vk::ColorComponentFlags::A,
                blend_enable: true,
                src_color_blend_factor: vk::BlendFactor::SRC_ALPHA,
                dst_color_blend_factor: vk::BlendFactor::ONE_MINUS_SRC_ALPHA,
                color_blend_op: vk::BlendOp::ADD,
                src_alpha_blend_factor: vk::BlendFactor::ONE,
                dst_alpha_blend_factor: vk::BlendFactor::ONE_MINUS_SRC_ALPHA,
                alpha_blend_op: vk::BlendOp::ADD,
            };

            let color_blending = vk::PipelineColorBlendStateCreateInfo::default()
                .logic_op_enable(false)
                .attachments(&[color_blend_attachment]);

            // Dynamic state for viewport and scissor
            let dynamic_states = [vk::DynamicState::VIEWPORT, vk::DynamicState::SCISSOR];
            let dynamic_state = vk::PipelineDynamicStateCreateInfo::default()
                .dynamic_states(&dynamic_states);

            // Pipeline layout
            let desc_layout = self.desc_set_layout.unwrap();
            let pipeline_layout_info = vk::PipelineLayoutCreateInfo::default()
                .set_layouts(&[desc_layout]);

            let pipeline_layout = self.context.device
                .create_pipeline_layout(&pipeline_layout_info, None)
                .map_err(|e| UiRenderError::PipelineCreationFailed(format!("Failed to create pipeline layout: {}", e)))?;

            self.pipeline_layout = Some(pipeline_layout);

            // Create graphics pipeline
            let pipeline_info = vk::GraphicsPipelineCreateInfo::default()
                .stages(&shader_stages)
                .vertex_input_state(&vertex_input_info)
                .input_assembly_state(&input_assembly)
                .viewport_state(&viewport_state)
                .rasterization_state(&rasterizer)
                .multisample_state(&multisampling)
                .depth_stencil_state(&depth_stencil)
                .color_blend_state(&color_blending)
                .dynamic_state(&dynamic_state)
                .layout(pipeline_layout);

            let pipeline = self.context.device
                .create_graphics_pipelines(vk::PipelineCache::null(), &[pipeline_info], None)
                .map_err(|(_, e)| UiRenderError::PipelineCreationFailed(format!("Failed to create pipeline: {}", e)))?[0];

            self.pipeline = Some(pipeline);

            // Cleanup shader modules
            self.context.device.destroy_shader_module(vert_shader, None);
            self.context.device.destroy_shader_module(frag_shader, None);
        }

        Ok(())
    }

    fn compile_shader(&self, source: &str, stage: naga::ShaderStage) -> Result<vk::ShaderModule, UiRenderError> {
        // Parse WGSL
        let module = naga::front::wgsl::parse_str(source)
            .map_err(|e| UiRenderError::ShaderError(format!("WGSL parse error: {:?}", e)))?;

        // Validate
        let mut validator = naga::valid::Validator::new(
            naga::valid::ValidationFlags::all(),
            naga::valid::Capabilities::empty(),
        );
        let info = validator.validate(&module)
            .map_err(|e| UiRenderError::ShaderError(format!("Shader validation error: {:?}", e)))?;

        // Compile to SPIR-V
        let options = naga::back::spv::Options::default();
        let spirv = naga::back::spv::write_vec(&module, &info, &options)
            .map_err(|e| UiRenderError::ShaderError(format!("SPIR-V generation error: {:?}", e)))?;

        unsafe {
            let create_info = vk::ShaderModuleCreateInfo::default()
                .code(&spirv);

            self.context.device
                .create_shader_module(&create_info, None)
                .map_err(|e| UiRenderError::ShaderError(format!("Failed to create shader module: {}", e)))
        }
    }

    fn update_descriptor_sets(&mut self) -> Result<(), UiRenderError> {
        unsafe {
            let desc_set = self.desc_set.unwrap();
            let uniform_buffer = self.uniform_buffer.unwrap();

            // Uniform buffer descriptor
            let buffer_info = vk::DescriptorBufferInfo {
                buffer: uniform_buffer,
                offset: 0,
                range: std::mem::size_of::<UiUniforms>() as u64,
            };

            let uniform_write = vk::WriteDescriptorSet::default()
                .dst_set(desc_set)
                .dst_binding(0)
                .descriptor_type(vk::DescriptorType::UNIFORM_BUFFER)
                .buffer_info(&[buffer_info]);

            // Image descriptor
            let texture = self.white_texture.as_ref().unwrap();
            let image_info = vk::DescriptorImageInfo {
                sampler: vk::Sampler::null(), // Not used for sampled image
                image_view: texture.image_view.vk(),
                image_layout: vk::ImageLayout::SHADER_READ_ONLY_OPTIMAL,
            };

            let image_write = vk::WriteDescriptorSet::default()
                .dst_set(desc_set)
                .dst_binding(1)
                .descriptor_type(vk::DescriptorType::SAMPLED_IMAGE)
                .image_info(&[image_info]);

            // Sampler descriptor
            let sampler_info = vk::DescriptorImageInfo {
                sampler: texture.image_sampler.vk(),
                image_view: vk::ImageView::null(),
                image_layout: vk::ImageLayout::UNDEFINED,
            };

            let sampler_write = vk::WriteDescriptorSet::default()
                .dst_set(desc_set)
                .dst_binding(2)
                .descriptor_type(vk::DescriptorType::SAMPLER)
                .image_info(&[sampler_info]);

            self.context.device.update_descriptor_sets(
                &[uniform_write, image_write, sampler_write],
                &[],
            );
        }

        Ok(())
    }

    /// Update screen size uniform.
    pub fn update_screen_size(&mut self, screen_size: Vec2) {
        if let (Some(buffer), Some(allocation)) = (&self.uniform_buffer, &self.uniform_allocation) {
            let uniforms = UiUniforms {
                screen_size: [screen_size.x(), screen_size.y()],
                _padding: [0.0, 0.0],
            };

            let mapped_ptr = self.context.map_buffer(allocation);
            unsafe {
                std::ptr::copy_nonoverlapping(
                    &uniforms as *const UiUniforms as *const u8,
                    mapped_ptr,
                    std::mem::size_of::<UiUniforms>(),
                );
            }
        }
    }

    /// Render a draw list.
    pub fn render(&mut self, draw_list: &DrawList, cmd: vk::CommandBuffer, screen_size: Vec2) {
        if draw_list.is_empty() {
            return;
        }

        // Update uniform buffer
        self.update_screen_size(screen_size);

        // Upload vertex data
        if let Some(ref mut vb) = self.vertex_buffer {
            let vertices = draw_list.vertices();
            let vertex_bytes = unsafe {
                std::slice::from_raw_parts(
                    vertices.as_ptr() as *const u8,
                    vertices.len() * std::mem::size_of::<UiVertex>(),
                )
            };
            vb.upload_data(vertex_bytes);
        }

        // Upload index data
        if let Some(ref mut ib) = self.index_buffer {
            let indices = draw_list.indices();
            let index_bytes = unsafe {
                std::slice::from_raw_parts(
                    indices.as_ptr() as *const u8,
                    indices.len() * std::mem::size_of::<u32>(),
                )
            };
            ib.upload_data(index_bytes);
        }

        unsafe {
            // Bind pipeline
            self.context.device.cmd_bind_pipeline(
                cmd,
                vk::PipelineBindPoint::GRAPHICS,
                self.pipeline.unwrap(),
            );

            // Bind descriptor set
            self.context.device.cmd_bind_descriptor_sets(
                cmd,
                vk::PipelineBindPoint::GRAPHICS,
                self.pipeline_layout.unwrap(),
                0,
                &[self.desc_set.unwrap()],
                &[],
            );

            // Set viewport
            let viewport = vk::Viewport {
                x: 0.0,
                y: 0.0,
                width: screen_size.x(),
                height: screen_size.y(),
                min_depth: 0.0,
                max_depth: 1.0,
            };
            self.context.device.cmd_set_viewport(cmd, 0, &[viewport]);

            // Set scissor
            let scissor = vk::Rect2D {
                offset: vk::Offset2D { x: 0, y: 0 },
                extent: vk::Extent2D {
                    width: screen_size.x() as u32,
                    height: screen_size.y() as u32,
                },
            };
            self.context.device.cmd_set_scissor(cmd, 0, &[scissor]);

            // Bind vertex buffer
            let vb = self.vertex_buffer.as_ref().unwrap();
            self.context.device.cmd_bind_vertex_buffers(
                cmd,
                0,
                &[vb.object()],
                &[0],
            );

            // Bind index buffer
            let ib = self.index_buffer.as_ref().unwrap();
            self.context.device.cmd_bind_index_buffer(
                cmd,
                ib.object(),
                0,
                vk::IndexType::UINT32,
            );

            // Draw each command
            let mut index_offset = 0u32;
            for cmd_info in draw_list.commands() {
                self.context.device.cmd_draw_indexed(
                    cmd,
                    cmd_info.index_count,
                    1,
                    index_offset,
                    cmd_info.vertex_offset,
                    0,
                );
                index_offset += cmd_info.index_count;
            }
        }
    }

    /// Clean up resources.
    pub fn destroy(&mut self) {
        unsafe {
            if let Some(pipeline) = self.pipeline.take() {
                self.context.device.destroy_pipeline(pipeline, None);
            }
            if let Some(layout) = self.pipeline_layout.take() {
                self.context.device.destroy_pipeline_layout(layout, None);
            }
            if let Some(layout) = self.desc_set_layout.take() {
                self.context.device.destroy_descriptor_set_layout(layout, None);
            }
            if let Some(pool) = self.desc_pool.take() {
                self.context.device.destroy_descriptor_pool(pool, None);
            }
            if let (Some(buffer), Some(allocation)) = (self.uniform_buffer.take(), self.uniform_allocation.take()) {
                self.context.free_buffer(buffer, allocation);
            }
        }
        self.vertex_buffer = None;
        self.index_buffer = None;
        self.white_texture = None;
    }
}

impl Drop for UiRenderer {
    fn drop(&mut self) {
        self.destroy();
    }
}

/// Errors that can occur in UI rendering.
#[derive(Debug, Clone)]
pub enum UiRenderError {
    /// Vulkan error occurred.
    VulkanError(String),
    /// Failed to create pipeline.
    PipelineCreationFailed(String),
    /// Failed to allocate buffers.
    BufferError(String),
    /// Failed to create texture.
    TextureError(String),
    /// Shader compilation error.
    ShaderError(String),
}

impl std::fmt::Display for UiRenderError {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        match self {
            UiRenderError::VulkanError(msg) => write!(f, "Vulkan error: {}", msg),
            UiRenderError::PipelineCreationFailed(msg) => write!(f, "Pipeline creation failed: {}", msg),
            UiRenderError::BufferError(msg) => write!(f, "Buffer error: {}", msg),
            UiRenderError::TextureError(msg) => write!(f, "Texture error: {}", msg),
            UiRenderError::ShaderError(msg) => write!(f, "Shader error: {}", msg),
        }
    }
}

impl std::error::Error for UiRenderError {}
